snyk

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -9,35 +9,24 @@ on:
 jobs:
   vulnerability-scan:
     runs-on: ubuntu-latest
-
-    env:
-      SNYK_TOKEN: 658c4f7e-b9a1-420d-8a88-cdadb1a7cfbc
-      SNYK_ORG: 658c4f7e-b9a1-420d-8a88-cdadb1a7cfbc
-      SNYK_TEST_EXCLUDE: build,generated
-
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up JDK 21
-        uses: actions/setup-java@v3
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-      - uses: snyk/actions/setup@0.4.0
-      - name: Install snyk-delta
-        run: |
-          npm config set prefix '~/.local/'
-          mkdir -p ~/.local/bin
-          export PATH="$HOME/.local/bin/:$PATH"
-          npm install -g snyk-delta
-          chmod +x ./snyk/snyk_delta_all_projects.sh
-      - name: Identify new vulnerabilities
-        run: ./snyk/snyk_delta_all_projects.sh --org=$SNYK_ORG --exclude=$SNYK_TEST_EXCLUDE -d
+      - uses: actions/checkout@v4
+      - name: Set up Snyk CLI to check for security issues
+        # Snyk can be used to break the build when it detects security issues.
+        # In this case we want to upload the SAST issues to GitHub Code Scanning
+        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
+
+        # For Snyk Open Source you must first set up the development environment for your application's dependencies
+        # For example for Node
+        #- uses: actions/setup-node@v4
+        #  with:
+        #    node-version: 20
+
         env:
-          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
-          MY_GITHUB_ACTOR: ${{ secrets.MY_GITHUB_ACTOR }}
-          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-      - name: Run code test
-        uses: snyk/actions/gradle@0.4.0
-        with:
-          command: code test
-          args: --org=${SNYK_ORG}
+          # This is where you will need to introduce the Snyk API token created with your Snyk account
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test
+        run: snyk code test --sarif
